
CREATE DATABASE BCCourseFinderDB;
GO


USE BCCourseFinderDB;
GO


CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Surname NVARCHAR(100) NOT NULL,
    IDNumber NVARCHAR(13) NOT NULL UNIQUE,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Phone NVARCHAR(20) NOT NULL,
    Address NVARCHAR(500) NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    DateCreated DATETIME DEFAULT GETDATE()
);
GO